#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:t arch:headline ^:nil
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:nil e:nil email:t f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:nil title:t toc:t todo:t |:t
#+TITLE: elect式Org-ｍode講座 
#+SUBTITLE: 
#+DATE: 
#+AUTHOR: 
#+EMAIL: e.tmailbank@gmail.com
#+LANGUAGE: ja
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.5.1 (Org mode 9.0.2)

#+LATEX_CLASS: koma-article
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER: \usepackage[backend=biber,bibencoding=utf8,style=authoryear-icomp]{biblatex}
#+LATEX_HEADER: \addbibresource{my-bib.bib}
#+LATEX_HEADER_EXTRA:
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:
#+STARTUP: indent overview inlineimages
* Org modeって何？
　 主にEmacsにおける文書作成システムです。これはEmacs（他にはSublimeText）内のシステムのため、使用にはまずそれのインストールが必要です。簡単に言ってしまえば、Emacsを使うことが出来る人が文書を作成したくなったら使うシステム、ということになります。

* Org ｍodeって何に使うの？
　 Org modeは論文などの書類を制作するツールで、わかりやすい仲間を挙げるとMicrosoftWord、LaTexらになります。
　具体的にどのような場面で使うのかというと、大学生ならば毎日のように提出を求められる（？）レポート、或いは論文などの場面が考えられます。それ以外にも何かしらの文章を作成するには使うことでしょう。またこのOrg Modeの機能の有用性から、これを小説執筆などにも用いることも可能です（この文章を書いている主もそのように使っています）。
　また応用機能として、HTML出力にも対応しており、ブログなどに用いることも可能ですが、こちらはあまり目にすることはありません。（利用例としては、Org modeのドキュメントがそれに当たるはずです。http://orgmode.org/manual/） 。
　余談となりますが、このOrg modeはQiitaの記事として出力することも出来ますし、GitHubのREADME.mdファイルの代替（README.orgとして保存する）としても機能させることが出来ます。

* Org modeって簡単に使うことが出来るの？
　 正直に申し上げると、中々に面倒臭いです。というのもこのシステムは更新こそ多いものの、それに対する日本語ドキュメントが非常に少ないため、英語ドキュメントを読むことが辛い主のような方には若干敷居が高いです。換言すれば、QiitaなどでOrg modeの最新情報が日本語で公開されないと使用に困難が伴うということです。英語が得意な方は是非とも翻訳してください。
　しかしながら、使い方を軽くでも学んでしまえばこれ以上ない文書作成ツールであることは自信を持っています。細かなタグ規則に捕らわれることはなく、また下手な赤線・青線が見栄えを損なわせたり（Word、貴方のことですよ）、自分の書いた数式が出力してみると謎記号になっていたりすることがなくなります。またこのシステムは様々な出力に対応しているため、複数の文書作成ソフトの利用方法を覚える必要性が無くなるということで、結果的に低コストで文書を作成することが出来るでしょう。

* 設定方法がわかりません
　 ここからはEmacsの設定等の話となります。Emacsの使い方に関しては後に主式の使い方を記事等で公開する予定ですが、ここでは割愛させて頂きます。簡単なチュートリアルについてはEmacsに搭載されているチュートリアルがいいでしょう。インストール方法についてはWindowsユーザならばプログラマーズ雑記帳のここのNTEmacs（http://yohshiy.blog.fc2.com/blog-entry-295.html） をおすすめします。それ以外のOSユーザならば、恐らくシェル上などからのインストールが出来るはずです。チュートリアルページヘは、起動した画面からEmacs Tutorialと書かれたリンクをクリックすることで向かうことが出来ます。恐らく英語ですが、下手な日本語の解説書を買うよりも直感的な理解が得られると思います。
　さて、ここからはEmacsの設定ファイルの問題となりますので理解に多少の困難がともなうと思いますが、初心者の方はそれが正常な反応なので不安になることはありません。
　第一の設定方法はこちらの主式のEmacs設定方法のページを参考にしてください。
x
