#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:t arch:headline ^:nil
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:nil e:nil email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:nil title:t toc:nil todo:t |:t
#+TITLE: 絵本制作（案）
#+SUBTITLE: 
#+DATE: 
#+AUTHOR: 筑波大学情報科学類2年 江畑 拓哉 (201611350)
#+LANGUAGE: ja
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.5.1 (Org mode 9.0.2)

#+LATEX_CLASS: elect-book
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER: 
#+LATEX_HEADER_EXTRA:
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:
#+STARTUP: indent overview inlineimages
* 一頁
#+LATEX: \newline
　ある年の暮の夜、旅人は暗く寒い夜道に身震いをした。
　ここは森の中。街は見えなかったが、手持ちに火の元はなくこのまま寝てしまうには些か不用心であった。
　
　ところが珍しいこともあり、焚かれた火とそれを囲む十ばかりの人が目についた。
　彼はその輪に割って入り一番近くに座っているそのフードを被った一人に、
　”そこに入れてはくれないか”と声を掛けた。
　構わない、という返答を受けその輪に加わる。見渡すとどうやら十二人のフードと杖が暖を取っているようだった。
　”何かの縁だ、十三人目としてこの十二の月をどう思う？”
　十二人目は旅人にこれを尋ねた。
　
* 二頁
#+LATEX: \newline
　十二人目は杖を火にかざした。炎は泡立ちその中に情景が浮かんだ。

　十二月は雪と寒さの月、小雪を眺めて別れを告げ始まりを待つ月。ふと開けた空は澄んだ冷たさで素肌に鋭利な境界を刻む。

* 三頁
#+LATEX: \newline
　十一月は木枯らし吹く中、冬の始まりに備える月。足元には霜の砕ける小気味良い音、空には澄んだ青。

* 四頁
#+LATEX: \newline
　十月は収穫と赤の月。焼けるような赤黄の木々に刈り入れた穀物、充実の月。そして別れに悲しむ月。

* 五頁
#+LATEX: \newline
　九月は涼の月。暑さ過ぎた先の、休息の月。早朝の高く青い空に描かれる薄い白。

* 六頁
#+LATEX: \newline
  八月は暑さの残る白雲と蛍火の月。日の下では色彩のキャンパス、月の下では一面の星空。

* 七頁
#+LATEX: \newline
  七月は日の満ちる月。暑さの上り坂、朝夕の涼しさ。

* 八頁
#+LATEX: \newline
  六月は日の登る月。暑さが肌に触れてくる感覚。梅雨の淑やかさと萌黄の奔流。
  
* 九頁
#+LATEX: \newline
  五月は調和の月。早苗の上に降り散る花弁。水路を流れる若い清水。

* 十頁
#+LATEX: \newline
  四月は咲き誇る月。とめどなく吹き出る命。物事の始まり。

* 十一頁
#+LATEX: \newline
  三月は発芽の月。未だに眠る者を揺する緩やかな一時。

* 十二頁
#+LATEX: \newline
  二月は残雪の月。浅眠の芽は嬉々として芽ぐみ始める。

* 十三頁
#+LATEX: \newline
  一月は眠りの中の始まりの月。物皆眠る床の外、小さく始まりを告げる。

* 十四頁
#+LATEX: \newline
  ”どれも良い”
彼は答えた。
”明日が良ければそれで良い”
　
　彼は礼を一つ置き、森を進んでいった。気がつけば夜は開けていた。
* 十五頁
#+LATEX: \newline
　”旅人らしい答えだ”
　打って変わってフードの中の若い声は問いかけた。それ以上は要らなかった。
　
　晴れ晴れとして、再び新たなもう一週が始まった。
