#+OPTIONS: ':nil *:t -:t ::t <:t H:2 \n:t arch:headline ^:nil
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:nil e:nil email:t f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:nil title:t toc:t todo:t |:t
#+TITLE: QR分解
#+SUBTITLE: 
#+DATE: 
#+AUTHOR: 情報科学類３年 江畑 拓哉 (201611350)
#+EMAIL: 
#+LANGUAGE: ja
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.5.1 (Org mode 9.0.2)

#+LATEX_CLASS: mybeamer
#+LATEX_CLASS_OPTIONS:[dvipdfmx,10pt,presentation]
#+LATEX_HEADER: \useoutertheme[subsection=false]{smoothbars}
#+LATEX_HEADER: \setbeamertemplate{footline}[page number]
#+LATEX_HEADER: \setbeamercolor{page number in head/foot}{fg=black}
#+LATEX_HEADER: \setbeamerfont{page number in head/foot}{size=\normalsize}
#+LATEX_HEADER_EXTRA:
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:
#+STARTUP: indent overview inlineimages
#+STARTUP: beamer
#+BEAMER_FRAME_LEVEL: 2

* 導入
** 導入
　行列を直交変換を用いて三角行列や対角行列と言った形に小さく圧縮したい。
　$\rightarrow$ そのような圧縮手法として ``QR分解'' が挙げられる。

　QR分解とはある行列 $\bm{A}$ を直交行列と三角行列に因数分解する手法で、分解される2つの条件に =三角行列である= という点のみが要求されるという意味でLU分解よりも広い範囲をカバーする。
*** LU分解の適用条件
:PROPERTIES:
:BEAMER_ENV: block
:BEAMER_COL: 1.00
:END:
分解する行列 $\bm{A}$ が正則行列であること

* 直交変換を用いた三角行列への変換 
** 　


　直交変換の一つであるハウスホルダー変形を行うことで、任意の行列 $\bm{A}\ \in \ \mathbb{R}^{m \times n}\ where\ m \geq n$ について上三角行列 $\bm{R}$ と 直交行列 $\bm{Q}\ \in\ \mathbb{R}^{m \times m}$ を用いた関係式を作ることが出来る。

\begin{align*}
\bm{A}\ \rightarrow\ \bm{Q}^T\bm{A}\ = \begin{pmatrix}R \\ 0\end{pmatrix}
&& where\ R\ \in\ \mathbb{R}^{n\times n}
\end{align*}

** $\bm{A}\ \in\ \mathbb{R}^{5\times4}$ である場合について考えた時
:PROPERTIES:
:BEAMER_opt: allowframebreaks
:END:
　最初のステップでは1列目の上から1番目より下の要素をゼロにする。

\begin{align*}
\bm{H}_1\bm{A} = \bm{H}_1
\begin{pmatrix}
\times & \times & \times & \times \\
\times & \times & \times & \times \\
\times & \times & \times & \times \\
\times & \times & \times & \times \\
\times & \times & \times & \times \\
\end{pmatrix}
=
\begin{pmatrix}
+ & + & + & + \\
0 & + & + & + \\
0 & + & + & + \\
0 & + & + & + \\
0 & + & + & + \\
\end{pmatrix}
\end{align*}

　ここで、 $+$ の値は $\times$ に比べて変形されて値が変わっています。直交行列である $\bm{H}_1$ の適用は、ハウスホルダー変換を行うことに等しい。

　次のステップでは変換した $\bm{A}$ に対して、前のステップと同様に2列目の上から2番目より下の要素をゼロにして、

\begin{align*}
\bm{H}_2
\begin{pmatrix}
\times & \times & \times & \times \\
0 & \times & \times & \times \\
0 & \times & \times & \times \\
0 & \times & \times & \times \\
0 & \times & \times & \times \\
\end{pmatrix}
=
\begin{pmatrix}
\times & \times & \times & \times \\
0 & + & + & + \\
0 & 0 & + & + \\
0 & 0 & + & + \\
0 & 0 & + & + \\
\end{pmatrix}
\end{align*}


\framebreak
　三番目のステップでも同様に変換して、

\begin{align*}
\bm{H}_3
\begin{pmatrix}
\times & \times & \times & \times \\
0 & \times & \times & \times \\
0 & 0 & \times & \times \\
0 & 0 & \times & \times \\
0 & 0 & \times & \times \\
\end{pmatrix}
=
\begin{pmatrix}
\times & \times & \times & \times \\
0 & \times & \times & \times \\
0 & 0 & + & + \\
0 & 0 & 0 & + \\
0 & 0 & 0 & + \\
\end{pmatrix}
\end{align*}

　四番目のステップでも同様にして、上三角行列 $\bm{R}$ を得ることが出来る。
　この変換を要約すると、

\begin{align*}
\bm{Q}^T\bm{A}=
\begin{pmatrix}
\bm{R} \\
\bm{0}
\end{pmatrix}
&& where\ \bm{Q}^T =\bm{H}_4\bm{H}_3\bm{H}_2\bm{H}_1
\end{align*}

　また、 $\bm{H}_i\ where\ \bm{A}\ \in\ \mathbb{R}^{m\times n}$ の構造は以下のようになる。

\begin{align}
\bm{H}_1 &= \bm{I} - 2\bm{u}_1\bm{u}_1^T && where\ u_1\ \in\ \mathbb{R}^m \nonumber \\
\bm{H}_2 &= 
\begin{pmatrix}
1 & 0 \\
0 & \bm{P}_2
\end{pmatrix}
&& where\ \bm{P}_2=\bm{I} - 2\bm{u}_2\bm{u}_2^T,\ \bm{u}_2\ \in\ \mathbb{R}^{m-1}
\nonumber \\ 
\bm{H}_3 &= 
\begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & \bm{P}_3 
\end{pmatrix}
&& where\ \bm{P}_3=\bm{I} - 2\bm{u}_3\bm{u}_3^T,\ \bm{u}_3\ \in\ \mathbb{R}^{m-2}
\tag{5.1}
\end{align}



　このようにして、単位行列に連続して小さくなっていくハウスホルダー変換を埋め込み、それと同時にベクトル $\bm{u}_i$ の次元も小さくなる。
　 
$\bm{H}_i$ がハウスホルダー変換でもあることは自明である。例えば

\begin{align*}
\bm{H_3} = \bm{I} - 2 \bm{u}^{(3)} \bm{u}^{(3)^T} 
&&  where\ \bm{u}^{(3)}=
\begin{pmatrix}
0 \\
0 \\
\bm{u}_3
\end{pmatrix}
\end{align*}

　尚、三角行列への変換は行列 $\bm{A}$ の圧縮と等しい。
** QR分解Ⅰ

*** 定理 5.1 QR分解
:PROPERTIES:
:BEAMER_ENV: block
:BEAMER_COL: 1.00
:END:
　どのような行列 $\bm{A}\ where\ \bm{A}\ \in\ \mathbb{R}^{m\times n},\ m \geq n$ についても直交行列によって上三角行列に変形することが出来る。またこの変形は以下の行列の圧縮に等しい。

\begin{align*}
\bm{A} = \bm{Q}
\begin{pmatrix}
\bm{R}\\
\bm{0}
\end{pmatrix}&& where\ &\bm{Q}\ \in\ \mathbb{R}^{m\times m}\ is\ orthogonal \\
             &&& \bm{R}\ \in\ \mathbb{R}^{n\times n}\ is\ upper\ triangular
\end{align*}
(orthogonal matrix=直交行列,upper triangular matrix=上三角行列)
　もし $\bm{A}$ が列について線形独立であるならば $\bm{R}$ は正則である。
