* Japanese:
 自然言語処理の1分野に対話システムという分野がある。昨今このシステムは複数の小問題を解決するシステムから構成されることが多く、それぞれのシステムにルールベース・機械学習を問わず様々な手法が用いられている。本研究では、特に日本語を対象とした対話システムを構築することを目指す。まず大まかな全体像を描き、次に主に深層学習の手法を用いてそれに必要となる手法をそれぞれ研究する。またこのようなシステムを構築する際に不可欠になる日本語のデータの収集法と、その前処理について調査する。
　つまり本研究で対象とする問題は以下の5テーマである。1つ目は日本語データの取り扱いについてである。TwitterやNTTが公開している日本語のデータを観察し、それらに含まれるデータにどのような性質があるのか、またどのような前処理を施すべきなのかを議論する。2つ目は不均衡なデータのクラス分類についてだ。不均衡なという意味は、各クラスの抽象度が違うということ、各クラスの教師データ数が異なるということを示している。3つ目は機械翻訳モデルを用いた対話モデルで、機械翻訳に使われているいくつかのモデルを1対1の応答対話を行うモデルに転用することを実験する。4つ目は文のスタイル変換で、いくつかのモデルに特に日本語の語尾変化を学習させる。日本語は特に語尾に性格や性別が結びついている場合が多く、対話システムを構築する際にこの変化を盛り込むことでユーザに親近感を与えることが出来ると考えられる。5つ目は深層学習のモデルを用いて対話システムを作成した場合の、エラー(不自然な文)検知を行う手法についてである。深層学習を用いて対話システムを作るモチベーションが低い理由として、精度が不安であるということがある。このテーマでは、何らかのエラー処理に繋げるため、特に不自然な文が作成されてしまった場合にそれを検知する技術を研究する。
* English:
  One of the fields in NLP (Natural Language Processing) is Dialogue systems. Recently, Dialogue systems are often built using many systems, each solving a different small problem for the main dialogue system. These systems use various methods such as rule-based, machine learning etc. In this report, I aimed at constructing a Dialogue System forcused in the Japanese language. First, I designed an abstract structure for the dialogue system, and next, I studied some of the required methods for this structure, using mainly deep learning techniques. In addition, I investigated the method for collecting and preprocessing Japanese data, which is indispensable for constructing this system.\\
  In other words, the subjects of this research were the following five themes. 1st, the dealing methods for Japanese data. I observed Japanese utterance data and conversation data from free data sets such as the corpus published by NTT(Nippon Telegraph and Telephone Corporation) and Twitter data and consider these natures, as well as some preprocessing methods for them. 2nd, the classification task for imbalanced data. The meaning of ``imbalance'' indicates that the difference of the abstraction degree of each class and the proportion of each class in data. 3rd, the conversation model using machine translation model. I tried some machine translation models for conversation model which responses 1-by-1 such as a general greeting.4th, the sentence style translation. I tried several models which I chose to learn translation of sentence style. In Japanese, the change at the sentence end (this research deals with the main agenda of style translation) affects people's detection of persona too much. So, I believe the style translation will lead the user of this Dialogue System to feel more comfortable by choosing the best style for its system. 5th, the error (in which sentences generated by some deep learning models) detection methods. The main reason of the low motivation for choosing deep learning models to build dialogue systems is the distrust of the ability of deep learning systems to build natural phrases, in comparing to rule-based models. In this theme, to connect some error handling, I experimented the detection method of unnatural sentence generated by my model which made in the 3rd theme.
